# [SERVIDOR][ENV][TYPE][FUNCTION(optional)][CARDINAL_NUMBER]
# SV = SERVIDOR
# |_ ENV [DEV = DEVELOP | QA = QA/TESTING | "" = PRODUCTION]
#    |_ TYPE [DB = DATABASE | CR = CORE APP | SB = STAND BY APP ]
#       |_ FUNCTION
#          |_ CARDINAL_NUMBER = [ (0-9)(0-9) = ORDER ]
---
application:
  children:
    app-network-develop:
      children:
        app-database-develop:
          hosts:
            SVDEVDB01:
              ansible_host: 10.70.1.12
        app-core-develop:
          hosts:
            SVDEVCR01:
              ansible_host: 10.70.1.13
        app-standby-develop:
          hosts:
            SVDEVSB01:
              ansible_host: 10.70.1.14
            SVDEVSB02:
              ansible_host: 10.70.1.15