Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
  
    config.vm.define "vm1" do |node|
        node.vm.network "private_network", ip: "10.70.1.12"
    end

    config.vm.define "vm2" do |node|
        node.vm.network "private_network", ip: "10.70.1.13"
    end

    config.vm.define "vm3" do |node|
        node.vm.network "private_network", ip: "10.70.1.14"
    end

    config.vm.define "vm4" do |node|
        node.vm.network "private_network", ip: "10.70.1.15"
    end
    
end
  